#!/usr/bin/env python3
"""Generate the tools handshake header from the pinned Atomic schema."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Sequence


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCHEMA = ROOT / "engine" / "Atomic-Stockfish" / "schemas" / "atomic-schema.json"
DEFAULT_OUTPUT = ROOT / "src" / "tools" / "atomic_data_schema.h"


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def render(schema_path: Path) -> str:
    raw = schema_path.read_bytes()
    schema = json.loads(raw.decode("utf-8"))
    record_size = schema.get("format", {}).get("record_size")
    require(schema.get("schema_id") == "legacy-atomic-v1", "unexpected schema id")
    require(schema.get("variant") == "atomic", "unexpected schema variant")
    require(record_size == 72, "unexpected Legacy Atomic V1 record size")
    require(schema.get("format", {}).get("atomic960") is False, "V1 must reject Atomic960")
    digest = hashlib.sha256(raw).hexdigest()
    handshake = json.dumps(
        {
            "schema_sha256": digest,
            "formats": {
                "legacy-atomic-v1": {
                    "read": True,
                    "write": True,
                    "record_size": record_size,
                }
            },
        },
        separators=(",", ":"),
    )
    empty_handshake = json.dumps(
        {"schema_sha256": digest, "formats": {}}, separators=(",", ":")
    )
    return f'''// Generated by script/generate_atomic_schema_header.py from the pinned
// engine/Atomic-Stockfish/schemas/atomic-schema.json. Do not edit by hand.
#ifndef TOOLS_ATOMIC_DATA_SCHEMA_H_INCLUDED
#define TOOLS_ATOMIC_DATA_SCHEMA_H_INCLUDED

#include <cstddef>
#include <string_view>

#if defined(__BYTE_ORDER__) && defined(__ORDER_LITTLE_ENDIAN__) \\
  && __BYTE_ORDER__ != __ORDER_LITTLE_ENDIAN__
#  error "legacy-atomic-v1 requires a little-endian host"
#endif

namespace Stockfish::Tools {{

inline constexpr std::string_view AtomicDataSchemaSha256 = "{digest}";
inline constexpr std::size_t LegacyAtomicV1RecordSize = {record_size};
inline constexpr bool LegacyAtomicV1Available = DATA_SIZE == 512;

inline constexpr std::string_view atomic_data_schema_json() noexcept
{{
    if constexpr (LegacyAtomicV1Available)
        return R"atomic-schema({handshake})atomic-schema";
    else
        return R"atomic-schema({empty_handshake})atomic-schema";
}}

}}  // namespace Stockfish::Tools

#endif  // TOOLS_ATOMIC_DATA_SCHEMA_H_INCLUDED
'''


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    schema = args.schema.resolve()
    output = args.output.resolve()
    expected = render(schema)
    if args.check:
        try:
            actual = output.read_text(encoding="utf-8")
        except OSError as error:
            raise AssertionError(f"cannot read generated schema header {output}: {error}") from error
        if actual.replace("\r\n", "\n") != expected:
            raise AssertionError(
                f"generated schema header is stale: run {Path(__file__).name}"
            )
        print(f"Atomic schema header verified schema={schema} output={output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="\n") as destination:
        destination.write(expected)
    print(f"Atomic schema header generated schema={schema} output={output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
