// Generated by script/generate_atomic_schema_header.py from the pinned
// engine/Atomic-Stockfish/schemas/atomic-schema.json. Do not edit by hand.
#ifndef TOOLS_ATOMIC_DATA_SCHEMA_H_INCLUDED
#define TOOLS_ATOMIC_DATA_SCHEMA_H_INCLUDED

#include <cstddef>
#include <string_view>

#if defined(__BYTE_ORDER__) && defined(__ORDER_LITTLE_ENDIAN__) \
  && __BYTE_ORDER__ != __ORDER_LITTLE_ENDIAN__
#  error "legacy-atomic-v1 requires a little-endian host"
#endif

namespace Stockfish::Tools {

inline constexpr std::string_view AtomicDataSchemaSha256 = "acca0f551f1c012c31a6c727dedccaebb7b5ebbc46810edb87e31bb208d5abe1";
inline constexpr std::size_t LegacyAtomicV1RecordSize = 72;
inline constexpr bool LegacyAtomicV1Available = DATA_SIZE == 512;

inline constexpr std::string_view atomic_data_schema_json() noexcept
{
    if constexpr (LegacyAtomicV1Available)
        return R"atomic-schema({"schema_sha256":"acca0f551f1c012c31a6c727dedccaebb7b5ebbc46810edb87e31bb208d5abe1","formats":{"legacy-atomic-v1":{"read":true,"write":true,"record_size":72}}})atomic-schema";
    else
        return R"atomic-schema({"schema_sha256":"acca0f551f1c012c31a6c727dedccaebb7b5ebbc46810edb87e31bb208d5abe1","formats":{}})atomic-schema";
}

}  // namespace Stockfish::Tools

#endif  // TOOLS_ATOMIC_DATA_SCHEMA_H_INCLUDED
